### PR TITLE
Rasa 2.6.2 compatibility

### PR DESCRIPTION
**Pull request by JulianGerhard21**
This PR should serve as an impetus to modify the repository for compatibility with Rasa 2.6.2 and possibly other versions.
Here is what I did so far:

- Changed Rasa dependency imports to 2.6.2 compatible statements. I assume when importing data that a `rasa data split nlu` has preceded.

```python
from rasa.shared.nlu.training_data.loading import load_data
from rasa.shared.utils.io import read_yaml

training_data = load_data(os.path.join(data_dir, "training_data.yml"))
test_data_path = os.path.join(data_dir, "test_data.yml")
```

- Introduced a new event loop to make sure, that Rasa's run_evaluation method is properly awaited.

```python
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
evaluation_result = loop.run_until_complete(run_evaluation(data_path, model_path))
```

This is probably not a neat way to solve it my concern was first to check whether functionality is guaranteed afterwards.

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @hsm207 will take a look at it as soon as possible ✨

**Comment by koaning** [comment]
I think [this line](https://github.com/RasaHQ/nlu-hyperopt/blob/master/requirements-dev.txt#L2) also needs an update.

@melindaloubser1, is there a reason why this project is currently tested against Rasa 1.10?

**Comment by melindaloubser1** [comment]
That was the last time it was updated & confirmed to work; it should be updated to be compatible with 2.x if possible

**Comment by JulianGerhard21** [comment]
I'd also recommend to evaluate if the following lines need to be checked for compatibility:

```    
for example in data.intent_examples:
```

since it may be the case that the `data_load` method/function has changed and the property `intent_examples` may no longer be existent.

**Comment by melindaloubser1** [comment]
Closing this as stale since the relevant version now would be rasa 3.0

**Comment by aaronbriel** [comment]
@melindaloubser1 please pardon me commenting on a closed PR, but are there plans to update this to work with Rasa 3.x? Thanks!

**Comment by aaronbriel** [comment]
@melindaloubser1 I started digging into this and I've created an upgrade branch. However, it looks like I don't have permission to push to it. What process should I be following here? Thanks!

**Comment by melindaloubser1** [comment]
Please fork the repo and open a PR from your fork to this upstream. Thanks!

**Comment by aaronbriel** [comment]
@melindaloubser1 FYI: https://github.com/RasaHQ/nlu-hyperopt/pull/18

**Pull request closed without merging**
